/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.andesscd.pki.clases;

/**
 *
 * @author abarrime
 */
public enum ResultadoVerificacion {

    VALIDO,
    OCSP_CRL_FUERA_DE_LINEA,
    CTL_NO_VALIDO,
    CTL_ERROR_FIRMA,
    CTL_ERROR_TIEMPO,
    CADENA_INCOMPLETA,
    TIENE_RESTRICCION_DE_NOMBRE_EXCLUIDA,
    TIENE_RESTRICCION_DE_NOMBRE_NO_PERMITIDA,
    TIENE_RESTRICCION_DE_NOMBRE_NO_DEFINIDA,
    TIENE_RESTRICCION_DE_NOMBRE_NO_SOPORTADA,
    RESTRICCION_DE_NOMBRE_INVALIDA,
    RESTRICCION_BASICA_INVALIDA,
    RESTRICCION_DE_POLITICAS_INVALIDA,
    EXTENCION_INVALIDA,
    CADENA_CICLICA,
    ESTADO_DE_REVOCACION_DESCONOCIDO,
    RAIZ_NO_CONFIABLE,
    USO_NO_VALIDO,
    FIRMA_DE_CERTIFICADO_NO_VALIDA,
    CADENA_DE_TIEMPO_INVALIDA,
    CERTIFICADO_EXPIRADO,
    CERTIFICADO_REVOCADO,
    SIN_ERROR,
    DOCUMENTO_ORIGINAL_MODIFICADO,
    FECHA_FIRMA_INCORRECTA,
    SNTP_NO_DISPONIBLE,
    ERROR_DESCONOCIDO,
    SIN_INFORMACION_OCSP,
    TIMESTAMP_NO_CONFIABLE,
    TIMESTAMP_NO_CORRESPONDE,
    TIMESTAMP_ERROR_DE_VALIDACION,
    FECHA_FIRMA_DESCONOCIDA,
    CERTIFICADO_NO_ENCONTRADO;

}
